version: '3.8'
services:
  solr1:
    build: ./solr
    ports:
     - "8983:8983"
    command:
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181
    depends_on:
      - zoo1

  solr2:
    build: ./solr
    ports:
     - "8984:8983"
    command:
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper:3.6
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
